Testing Pandas

In [19]:
import pandas as pd

df = pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})
dff = pd.DataFrame({'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']})
print(df)
print(dff)
dfffff= pd.DataFrame({'name':['rashed','raze'],'dep':['cse','ano']})
print(dfffff)




dfff = pd.Series([1, 2, 3, 4, 5])
print(dfff)

dffff = pd.Series([30, 35, 40], index=['2015 Sales', '2016 Sales', '2017 Sales'], name='Product A')
print(dffff)



#  List to Series and DataFrame
data = [1,2,3,4,5]
s = pd.Series(data)
s

d = pd.DataFrame(s)
d


# List to Direct DataFrame
datas = [5,4,3,2,1]
dat = pd.DataFrame(datas,columns=['num'])
dat

   Yes   No
0   50  131
1   21    2
             Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.
     name  dep
0  rashed  cse
1    raze  ano
0    1
1    2
2    3
3    4
4    5
dtype: int64
2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

   num
0    5
1    4
2    3
3    2
4    1

In [29]:
datass = dat["num"]
datass

0    5
1    4
2    3
3    2
4    1
Name: num, dtype: int64

In [18]:
type(datass)

pandas.core.series.Series

In [23]:
daTa = [[1,2],[3,4],[5,6]]
dATA = pd.DataFrame(daTa,columns=["num1","num2"])
dATA

   num1  num2
0     1     2
1     3     4
2     5     6

Now Series

In [27]:
daTA = dATA[['num1','num2']]
daTA

   num1  num2
0     1     2
1     3     4
2     5     6

In [28]:
type(daTA)

pandas.core.frame.DataFrame