Dictionary to DataFrame or Series

In [1]:
import pandas as pd

In [2]:
data = {
    'name':['rashed','sabit','prio'],
    'age':[23,24,23],
    'city':['jamalpur','serpur','rangpur']
}

In [3]:
data

{'name': ['rashed', 'sabit', 'prio'],
 'age': [23, 24, 23],
 'city': ['jamalpur', 'serpur', 'rangpur']}

In [4]:
name_series = pd.Series(data['name'],name='Name')
name_series

0    rashed
1     sabit
2      prio
Name: Name, dtype: object

In [5]:
df = pd.DataFrame(data)
df

     name  age      city
0  rashed   23  jamalpur
1   sabit   24    serpur
2    prio   23   rangpur

In [6]:
age_series = df['age']
age_series

0    23
1    24
2    23
Name: age, dtype: int64

In [7]:
city_series = df['city']
city_series

0    jamalpur
1      serpur
2     rangpur
Name: city, dtype: object

Set and Tuple to DataFrame or Series

In [8]:
s1 = {1,2,3,4,5,6,7,8,9,10}
s= pd.Series(list(s1))

In [9]:
s

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [10]:
df1 = pd.DataFrame(s1)
df1

    0
0   1
1   2
2   3
3   4
4   5
5   6
6   7
7   8
8   9
9  10

In [11]:
type(df1)

pandas.core.frame.DataFrame

In [12]:
t =(1,2,3,4,5)
s2 = pd.Series(t)
s

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [13]:
df2 = pd.DataFrame(t)
df2

   0
0  1
1  2
2  3
3  4
4  5

In [14]:
type(df2)

pandas.core.frame.DataFrame

In [15]:
df2.head()

   0
0  1
1  2
2  3
3  4
4  5

In [16]:
df2.describe()

              0
count  5.000000
mean   3.000000
std    1.581139
min    1.000000
25%    2.000000
50%    3.000000
75%    4.000000
max    5.000000

In [17]:
data = {
    'age':[1,2,3,4,5,6,7,8],
    'Salary':[10000,20000,30000,40000,50000,60000,70000,80000]
}
d = pd.DataFrame(data)

In [18]:
d

   age  Salary
0    1   10000
1    2   20000
2    3   30000
3    4   40000
4    5   50000
5    6   60000
6    7   70000
7    8   80000

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     3 non-null      int64
 2   city    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [21]:
d.dtypes

age       int64
Salary    int64
dtype: object

In [22]:
d['age'] = d['age'].astype('int32')
d['Salary'] = d['Salary'].astype('int32')

In [23]:
d.dtypes

age       int32
Salary    int32
dtype: object

In [24]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     8 non-null      int32
 1   Salary  8 non-null      int32
dtypes: int32(2)
memory usage: 196.0 bytes

In [25]:
d['age'] = d['age'].astype('int16')
d['Salary'] = d['Salary'].astype('int16')

In [26]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     8 non-null      int16
 1   Salary  8 non-null      int16
dtypes: int16(2)
memory usage: 164.0 bytes